spring:
  application:
    name: merge_xml
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog-master.yaml
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false
  sql:
    init:
      mode: always

merge-xml:
  currency-code: 810
  due-date: 10d
  file-name: Total.xml
  max-count-file: 10
  min-count-file: 1
  min-payment: 10
  max-payment: 999999999999.99
  max-result-file-weight: 500KB